// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sgi.Infrastructure.Data;

#nullable disable

namespace Sgi.Infrastructure.Migrations
{
    [DbContext(typeof(SgiDbContext))]
    [Migration("20260211120012_AddCobrancaCreditoAcordoPolitica")]
    partial class AddCobrancaCreditoAcordoPolitica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Sgi.Domain.Contabilidade.ContaContabil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoReferencialSped")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Natureza")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContasContabeis", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Contabilidade.LancamentoContabil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Historico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LancamentoFinanceiroId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LancamentosContabeis", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Contabilidade.MapeamentoPlanoContasContabil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaCreditoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaDebitoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlanoContasId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoLancamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MapeamentosPlanoContasContabeis", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Contabilidade.PartidaContabil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CentroCustoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaContabilId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LancamentoContabilId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LancamentoContabilId");

                    b.ToTable("PartidasContabeis", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Contabilidade.PeriodoContabil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompetenciaFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompetenciaInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FechadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PeriodosContabeis", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.Anexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CriadoPorUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<long>("Tamanho")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoEntidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Anexos", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnidadeOrganizacionalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Enderecos", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DadosAntesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("DadosDepoisJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LogsAuditoria", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.NotificacaoConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinatariosJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiasAntesVencimento")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LimiteValor")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificacoesConfig", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.NotificacaoEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinatariosJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LidoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificacoesEventos", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.Organizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModulosAtivos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Site")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organizacoes", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.Papel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Papeis", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.PapelPermissao", b =>
                {
                    b.Property<Guid>("PapelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PermissaoId")
                        .HasColumnType("TEXT");

                    b.HasKey("PapelId", "PermissaoId");

                    b.ToTable("PapeisPermissoes", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Permissoes", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimentoAbertura")
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pessoas", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Raca")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnidadeOrganizacionalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pets", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.UnidadeOrganizacional", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtributosExtrasJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoInterno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UnidadesOrganizacionais", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.UserCondoMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnidadeOrganizacionalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserCondoMemberships", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailLogin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Idioma")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.UsuarioPapelOrganizacao", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PapelId")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId", "OrganizacaoId", "PapelId");

                    b.ToTable("UsuariosPapeisOrganizacao", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnidadeOrganizacionalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Veiculos", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Core.VinculoPessoaOrganizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnidadeOrganizacionalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VinculosPessoaOrganizacao", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.AbonoFinanceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LancamentoFinanceiroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Percentual")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AbonosFinanceiros", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.AcordoCobranca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPrimeiraParcela")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAcordo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalOriginal")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnidadeOrganizacionalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AcordosCobranca", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.AcordoParcela", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AcordoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CobrancaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PagoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AcordosParcelas", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.CentroCusto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CentrosCusto", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.ChargeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoOpcional")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExigeReserva")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FinanceCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GeraCobrancaAutomatica")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PermiteAlterarValor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorPadrao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItensCobrados", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.ContaFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Agencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Banco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Moeda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroConta")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContasFinanceiras", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.CotaCondominial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompetenciaFim")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompetenciaInicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlanoContasId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnidadeOrganizacionalId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CotasCondominio", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.DocumentoCobranca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataBaixa")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentificadorExterno")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LancamentoFinanceiroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinhaDigitavel")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QrCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlPagamento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DocumentosCobranca", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.FinanceAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalhes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FinanceAudits", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.LancamentoFinanceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CentroCustoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContaFinanceiraId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCompetencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParcelaNumero")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParcelaTotal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlanoContasId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LancamentosFinanceiros", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.LancamentoPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContaFinanceiraId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstornadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstornoMotivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LancamentoFinanceiroId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LancamentosPagamentos", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.LancamentoRateado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CentroCustoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LancamentoOriginalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnidadeOrganizacionalId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorRateado")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LancamentosRateados", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.LeituraConsumo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Competencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Consumo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LeituraAnterior")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LeituraAtual")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MedidorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LeiturasConsumo", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.MedidorConsumo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroSerie")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnidadeOrganizacionalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MedidoresConsumo", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.MovimentoBancario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaBancariaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LancamentoFinanceiroId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnidadePagamentoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MovimentosBancarios", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.PlanoContas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlanosContas", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.PoliticaCobranca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CorrecaoMensalPercentual")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasCarencia")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("JurosMensalPercentual")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MultaPercentual")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PoliticasCobranca", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.PrevisaoOrcamentaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlanoContasId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorPrevisto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrevisoesOrcamentarias", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.RegraRateio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfiguracaoJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoBase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegrasRateio", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.UnidadeCobranca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AcordoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CentroCustoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Competencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContaBancariaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PagoEm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParcelaNumero")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParcelaTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnidadeOrganizacionalId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UnidadesCobrancas", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.UnidadeCreditoMovimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CobrancaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstornadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstornoMotivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PagamentoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnidadeOrganizacionalId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UnidadesCreditos", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Financeiro.UnidadePagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CobrancaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ComprovanteAnexoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContaBancariaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UnidadesPagamentos", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Operacao.Chamado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPrazoSla")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PessoaSolicitanteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prioridade")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResponsavelPessoaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResponsavelUsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SlaHoras")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnidadeOrganizacionalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chamados", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Operacao.ChamadoHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalhes")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResponsavelPessoaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChamadoHistoricos", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Operacao.RecursoReservavel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloqueiosJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Capacidade")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExigeAprovacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JanelaHorarioFim")
                        .HasColumnType("TEXT");

                    b.Property<string>("JanelaHorarioInicio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LimitePorUnidadePorMes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegrasJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnidadeOrganizacionalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecursosReservaveis", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Operacao.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AprovadorPessoaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LancamentoFinanceiroId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizacaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PessoaSolicitanteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecursoReservavelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnidadeOrganizacionalId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reservas", (string)null);
                });

            modelBuilder.Entity("Sgi.Domain.Contabilidade.PartidaContabil", b =>
                {
                    b.HasOne("Sgi.Domain.Contabilidade.LancamentoContabil", null)
                        .WithMany("Partidas")
                        .HasForeignKey("LancamentoContabilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sgi.Domain.Contabilidade.LancamentoContabil", b =>
                {
                    b.Navigation("Partidas");
                });
#pragma warning restore 612, 618
        }
    }
}
